[versions]
agp = "8.7.0"
kotlin = "1.9.24"
junit = "4.13.2"
jetbrainsKotlinJvm = "1.9.24"
okhttp = "4.12.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

